### PR TITLE
Added vagrant building support script

### PR DESCRIPTION
**Pull request by lzap**
Please do not merge, WIP.

### CODE REVIEW

**Comment by lzap** [comment]
FYI to test this do `repoowner=lzap branch=adding-vagrant-support VAGRANT_DEFAULT_PROVIDER=rackspace vagrant up el6`

**Comment by lzap** [comment]
@mhulan I just booted the image: http://downloads.theforeman.org/livecd/nightly/

It says: Permission denied for /home/livecd/foreman_setup.sh - it is missing execute permission.

I assume it requires internet connection for 8.8.8.8 google public dns. Is this the only requirement for internet connection?

Also my instance got incorrect IP address. My virt nat net is .122.0 it somehow configured the primary interface as .232.2. Is this intentional? Thanks for help.

**Comment by lzap** [comment]
@ares just to bring your attention. Would you mind spinning the ISO from above telling me what can be possibly wrong? Thanks.

**Comment by ares** [comment]
> It says: Permission denied for /home/livecd/foreman_setup.sh - it is missing execute permission.

AFAIK this was intentional so we can debug before the script is run, it should be trivial to chmod in %post ks template just after it's copied inside. see https://github.com/theforeman/foreman-live/blob/master/foreman-live-centos.ks#L756

> I assume it requires internet connection for 8.8.8.8 google public dns. Is this the only requirement for internet connection?

As you can see in https://github.com/theforeman/foreman-live/blob/master/foreman_setup.sh we also try to sync clock using ntp so we have right time before CA creates any certificate. Other than that there are connections that foreman-installer (or staypuft-installer) initiates, e.g. it downloads latest discovery images.

> Also my instance got incorrect IP address. My virt nat net is .122.0 it somehow configured the primary interface as .232.2. Is this intentional? Thanks for help.

We set static networking. The reason was that we didn't want to rely on any existing DHCP. Also you can adjust networking on first installer screen. So if you have .122.0 network you can reconfigure your host NIC using staypuft-installer. See https://github.com/theforeman/foreman-live/blob/master/foreman-live-centos.ks#L39 for static network configuration.

I think you've automated what we had, now it may be time to improve the image features itself.

**Comment by ares** [comment]
@lzap the livecd you linked works for me as expected (with glitches you described in previous comment), there was an error related to foreman-release-scl package which seems to be unrelated.

**Comment by lzap** [comment]
RTM

**Comment by ares** [comment]
Thanks @lzap, merging!

**Pull request merged**
