### PR TITLE
CentOS 7 based new live image

### PR DESCRIPTION
**Pull request by lzap**
WORK IN PROGRESS, I will push as we go.

### CODE REVIEW

**Comment by ares** [comment]
Did you remove debian livecd script? Maywe we should create branch or separate it into directories?

**Comment by lzap** [comment]
Oh yeah, I did not mean it. Will create a subdir maybe?

**Comment by lzap** [comment]
Pushed to `aux/debian` subdirectory, thanks.

**Comment by lzap** [comment]
Squashed, Jenkins is ready. Merging to get the first V2 nightly build.

**Comment by lzap** [comment]
http://ci.theforeman.org/job/packaging_foreman_livecd/

**Comment by lzap** [comment]
Build done! http://downloads.theforeman.org/livecd/nightly/

**Pull request merged**
