### PR TITLE
Added missing localhost entries

### PR DESCRIPTION
**Pull request by lzap**
PostgreSQL was not comping up due to localhost not resolving:

  ping localhost

This was not working due to missing entry in `/etc/hosts` which we overwrite.

I see few other glitches when trying the installer (issues with yum). I will
likely add more commits into this PR, please do not merge yet.

### CODE REVIEW

**Comment by lzap** [comment]
Foreman-installer now works, even in the offline mode (with default parameters). @mbacovsky please review, once you merge nightly will be built automatically in 30 mins (approx)

Next steps: installation script, turn on networking by default, install certificate into firefox

**Comment by mbacovsky** [comment]
In https://github.com/lzap/foreman-live/blob/missing-localhost/build-livecd#L51 there is `./build-live-root` instead of `./build-livecd-root`.

**Comment by lzap** [comment]
Oh right, fixed.

## 

Later,
 Lukas #lzap Zapletal

**Comment by mbacovsky** [comment]
:+1:  Works nice, thanks @lzap  :construction_worker:

**Comment by lzap** [comment]
Ok pushed. Can we give push permissions to @mbacovsky please @ohadlevy ? Thanks :-)

**Pull request merged**
